# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileHealth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileHealth
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'MobileHealthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MobileHealth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileHealth-tvOS

  target 'MobileHealth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
